// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOkOj14yg0gqeRr7X6lohvdyoTQ4blqA4',
    appId: '1:859034834698:web:3455471bdca328a7990cf3',
    messagingSenderId: '859034834698',
    projectId: 'weatherappvinay',
    authDomain: 'weatherappvinay.firebaseapp.com',
    storageBucket: 'weatherappvinay.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkOv7uUqNhGgJJ7yTJY4UR9wzOnvnw8Ac',
    appId: '1:859034834698:android:875adae7d579228a990cf3',
    messagingSenderId: '859034834698',
    projectId: 'weatherappvinay',
    storageBucket: 'weatherappvinay.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2nYQ_IQj-c-LOtAy0nUR8dWaOFG80DvM',
    appId: '1:859034834698:ios:dbcda00adffc42d6990cf3',
    messagingSenderId: '859034834698',
    projectId: 'weatherappvinay',
    storageBucket: 'weatherappvinay.appspot.com',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2nYQ_IQj-c-LOtAy0nUR8dWaOFG80DvM',
    appId: '1:859034834698:ios:95a3ff1ed58707da990cf3',
    messagingSenderId: '859034834698',
    projectId: 'weatherappvinay',
    storageBucket: 'weatherappvinay.appspot.com',
    iosBundleId: 'com.example.weatherapp.RunnerTests',
  );
}
